### ISSUE TITLE
Tasks

### ISSUE THREAD

**Issue by NickBonavia** [NickBonavia/CrossyLogs#1]
We need to begin with the sequential version of CrossyLogs before we move onto parallelizing it. Below are my proposed tasks based on architecture discussed.

- [x] Create abstract Entity class.
- [ ] Create a subclass of Entity for the Log game-obj.
- [ ] Create a subclass of Entity for the Player
- [ ] Create an image loader for game assets
- [ ] Implement Draw method in Game class
- [ ] Implement Update method in Game class

**Comment by geoRunstar** [comment]
Done
